// export const DISPLAY_ENTRIES = 'DISPLAY_ENTRIES';
// export const ADD_EVENT = 'ADD_EVENT';
export const SELECT_EVENT = 'SELECT_EVENT';
export const GET_EVENTS_DATA = 'GET_EVENTS_DATA';
export const GET_EVENTS_DATA_RECEIVED = 'GET_EVENTS_DATA_RECEIVED';
export const GET_EVENTS_DATA_ERROR = 'GET_EVENTS_DATA_ERROR';
// export const TOGGLE_ACTIVE = 'TOGGLE_ACTIVE';
